
[env:esp32-s3-supermini]
platform = espressif32
board = lolin_s3_mini
framework = arduino
monitor_speed = 115200

; Aumentar a partição de APP e criar espaço para LittleFS
board_build.partitions = default.csv 
board_build.filesystem = littlefs

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0
    mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display @ ^3.0.12
    bblanchon/ArduinoJson @ ^7.0.3
    adafruit/Adafruit GFX Library @ ^1.11.9
